version: '3'

services:
  mirotalk-nms:
    container_name: mirotalk-nms
    image: mirotalk/nms:latest
    volumes:
      - ./src/config.js:/app/src/config.js:ro # Yollarda oxirgi slashni olib tashlang
      # - /etc/letsencrypt/live/your-domain-name/fullchain.pem:/app/src/cert.pem:ro
      # - /etc/letsencrypt/live/your-domain-name/privkey.pem:/app/src/key.pem:ro
    ports:
      - '1935:1935'
      - '8081:8081'
      - '8043:8043'
    restart: unless-stopped
    environment:
      - SERVER_PORT=8080
      - MONGO_USERNAME=myusername
      - MONGO_PASSWORD=mypassword
      - MONGO_DATABASE=Starlab
      - MONGO_PORT=27017
    env_file:
      - .env
